pdf: G114_Aparicio_Esteban_prac7.tex #bibliography.bib
	pdflatex -synctex=1 -interaction=nonstopmode G114_Aparicio_Esteban_prac7.tex
	#biber G114_Aparicio_Esteban_prac7
	#pdflatex -synctex=1 -interaction=nonstopmode G114_Aparicio_Esteban_prac7.tex
	#pdflatex -synctex=1 -interaction=nonstopmode G114_Aparicio_Esteban_prac7.tex
	#xreader G114_Aparicio_Esteban_prac7.pdf
