pdf: G114_Aparicio_Esteban_prac6.tex #bibliography.bib
	pdflatex -synctex=1 -interaction=nonstopmode G114_Aparicio_Esteban_prac6.tex
	#biber G114_Aparicio_Esteban_prac6
	#pdflatex -synctex=1 -interaction=nonstopmode G114_Aparicio_Esteban_prac6.tex
	#pdflatex -synctex=1 -interaction=nonstopmode G114_Aparicio_Esteban_prac6.tex
	xreader G114_Aparicio_Esteban_prac6.pdf 
